server:
  port: 9090
spring:

  application:
    name: matrimony-app

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: jdbc:mysql://localhost:3306/matrimony?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: matrimony_app
    password: StrongPass@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # none | validate | update | create | create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

otp:
  length: 6
  expiry-minutes: 5
  max-verification-attempts: 3
  resend-interval: 60
  resend-limit: 3

photo:
  max-count: 3
  max-file-size: 2000000

token:
  secret: "matrimony-secret-key-very-secure-and-long-enough-256bits"
  expiry: 600000

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

aws:
  s3:
    region: ap-southeast-1
    bucket-name: matrimony-user-photos
    prefix: profile-photos
  dynamodb:
    region: ap-southeast-1
    table-name: matrimony-users
    endpoint: http://localhost:8000
